### PR TITLE
Console Easter Egg

### PR DESCRIPTION
**Pull request by jhancock532**
#### [Link to Ticket On Codebase](https://projects.torchbox.com/projects/contentful-careers-page/tickets/96)

Logs a console message across the careers site& also displays a torchbox themed image on Chromium based browsers. Adds roughly 4kb of extra overhead to the website. Open devtools on any page to view.

Doesn't work on Firefox (doesn't support SVG background image in console).

#### [Link to preview site page with component](https://careers-cpsvkjkz0-careers-site.vercel.app/careers)

<details>
  <summary>Screenshots</summary>
image

N.B: This is not especially responsive.
image

</details>

## MR Checklist

- [x] Add a description of your pull request and instructions for the reviewer to verify your work.
- [x] If your pull request is for a specific ticket, link to it in the description.
- [x] Stay on point and keep it small so the merge request can be easily reviewed.
- [x] Consider adding unit tests, especially for bug fixes. If you don't, tell us why.
- [x] Tests and linting passes.
- [x] Consider updating documentation. If you don't, tell us why.
- [x] If relevant, list the environments / browsers in which you tested your changes.

### CODE REVIEW

**Review by Morsey187 — CHANGES_REQUESTED** [review]
This looks good, I wonder if we can move this to somewhere we can avoid running the useEffect on every page load, perhaps `_app.js` might work

**Comment by jhancock532** [comment]
Updated to remove the useEffect, adding the console logs to `_app.tsx`. Note that the console now logs in the terminal as well, this is slightly awkward. 

Getting feedback and confirmation on copy from the project team.

image

**Comment by Morsey187** [comment]
> Updated to remove the useEffect, adding the console logs to `_app.tsx`. Note that the console now logs in the terminal as well, this is slightly awkward.
> 
> Getting feedback and confirmation on copy from the project team.
> 
> image

@jhancock532 We can keep the useEffect as this will prevent it running on the server I believe, the problem was with it mounting on everypage render, if we keep it inside the app file it should only mount once

**Comment by jhancock532** [comment]
Thank you for adding this fix, much appreciated!

**Pull request merged**
